CREATE TABLE students (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  email VARCHAR(200) NOT NULL UNIQUE,
  course VARCHAR(150),
  joined DATE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
